### ISSUE TITLE
--input folder command line isn't working

### ISSUE THREAD

**Issue by Yoda-Canada** [lmpham1/cool_ssg_generator#2]
### Command:
`python main.py --input Lab1`

### Directory Hierarchy:

![directory hierarchy](https://user-images.githubusercontent.com/55161917/133829347-1d7670bb-1dfc-4c5b-b5cd-8a4bdf31d075.png)

### ERROR:
![issue 2](https://user-images.githubusercontent.com/55161917/133828953-6717b61c-81f5-4dd0-81e8-f83564495600.png)

### Expected output:
`The tool should generate a  .html files in the '/dist' folder.`

**Comment by lmpham1** [comment]
fixed with commit https://github.com/lmpham1/cool_ssg_generator/commit/5ca42109eaa46f8c1b3b7fa3f6def9c96019307e - "fixed directory input not working"
