### ISSUE TITLE
Use os.path.join() to create paths vs. strings

### ISSUE THREAD

**Issue by humphd** [lmpham1/cool_ssg_generator#6]
Instead of creating paths out of strings, do it in a cross-platform way with [os.path.join()](https://docs.python.org/3/library/os.path.html#os.path.join), for example: https://github.com/lmpham1/cool_ssg_generator/blob/master/helper.py#L15

**Comment by lmpham1** [comment]
I was struggling a bit with figuring out "/" and "\" in the pathing. I have changed most of the code that needs pathing to use `os.path.join()` and other `os.path` functions with the commit 169195d22f35f0d521acb9163891027db72eb426
