### ISSUE TITLE
Don't add tool name to generated output

### ISSUE THREAD

**Issue by humphd** [lmpham1/cool_ssg_generator#7]
I think your users will find [this](https://github.com/lmpham1/cool_ssg_generator/blob/master/helper.py#L41). frustrating.  They only want to see the final HTML, not which tool generated it.

**Comment by lmpham1** [comment]
Hey @humphd, thanks for pointing this out.
I originally used it to generate the sample files, but forgot to remove it. I have now changed it to displaying the input folder name instead in the `index.html` file
